### ISSUE TITLE
not a bug but a noob question

### ISSUE THREAD

**Issue by noonies** [acheong08/ChatGPT#490] opened 2023-01-27 07:12 UTC
i have a problem when im trying to run it in replit.

"UnboundLocalError: local variable 'driver' referenced before assignment"

i searched everywhere but no luck.

**Comment by simonfalke-01** [comment] 2023-01-27 10:18
Having the same issue here.

**Comment by acheong08** [comment] 2023-01-27 11:15
Chromedriver issue. Duplicate of https://github.com/acheong08/ChatGPT/issues/381

**Closed by acheong08** 2023-01-27 11:15 UTC
Labels: bug

**Comment by simonfalke-01** [comment] 2023-01-27 12:28
I just had to install Chrome to fix this issue. I'm using macOS.
