### ISSUE TITLE
ValueError: PUID is required

### ISSUE THREAD

**Issue by kaland777** [acheong08/ChatGPT#1260] opened 2023-04-04 11:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Since yesterday I am getting this error, before it worked perfectly, the error is found in the OpenAIAuth.py file in the line puid = puid or os.environ.get("PUID"), I have tried to add the _puid field that appears in the cookies of my chatgpt plus session (paid version) but other errors appear that I can not identify. I have tried from different computers and ips but the results are the same

D:\AI\venv\lib\site-packages\OpenAIAuth.py", line 38, in __init__

### Steps to reproduce the problem

chatbot = Chatbot(config={
    "email": "my email",
    "password": "my pass",
})
for data in chatbot.ask("some prompt"):
    if prev_text == "":
        chat_id = data["conversation_id"]
    prev_text = data["message"]
print(prev_text)

### What should have happened?

Connect to chatgpt

### Version where the problem happens

4.1.1

### What Python version are you running this with?

3.9 and 3.10

### What is your operating system ?

Windows, Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
D:\AI\venv\lib\site-packages\revChatGPT\__init__.py:29: UserWarning: The current Python is not a recommended version, 3.10+ is recommended
  warn(warning)
Traceback (most recent call last):
  File "D:\AI\chatgpt\testing.py", line 8, in <module>
    chatbot = Chatbot(config={
  File "D:\AI\venv\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\AI\venv\lib\site-packages\revChatGPT\V1.py", line 163, in __init__
    self.__check_credentials()
  File "D:\AI\venv\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\AI\venv\lib\site-packages\revChatGPT\V1.py", line 187, in __check_credentials
    self.login()
  File "D:\AI\venv\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\AI\venv\lib\site-packages\revChatGPT\V1.py", line 321, in login
    auth = Authenticator(
  File "D:\AI\venv\lib\site-packages\OpenAIAuth.py", line 38, in __init__
    raise ValueError("PUID is required")
ValueError: PUID is required

Process finished with exit code 1
```

**Comment by acheong08** [comment] 2023-04-04 13:03
Duplicate of #1236

**Closed by acheong08** 2023-04-04 13:03 UTC

**Comment by sunjiadai** [comment] 2023-04-06 09:45
still can't solve it
