### ISSUE TITLE
Can not use the agent to request, may I ask how to solve

### ISSUE THREAD

**Issue by RavenCri** [acheong08/ChatGPT#1359] opened 2023-04-22 05:19 UTC
![image](https://user-images.githubusercontent.com/39519250/233764150-0ede4489-9524-49c6-bbf8-c9212bca2aca.png)

**Comment by acheong08** [comment] 2023-04-22 07:18
Duplicate of https://github.com/acheong08/ChatGPT/issues/987

**Closed by acheong08** 2023-04-22 07:18 UTC
Labels: question
