### ISSUE TITLE
[Bug]: V1 6.3.5(lastest version)OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)

### ISSUE THREAD

**Issue by WhiteCranes** [acheong08/ChatGPT#1435] opened 2023-06-24 03:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)

### Steps to reproduce the problem

setted access_token,PUID
used gpt-4-mobile
used V1 6.3.5(lastest version)

### What should have happened?

NOTHING SHOULD HAPPEN

### Version where the problem happens

V1 6.3.5(lastest version)

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
none
```

**Comment by acheong08** [comment] 2023-06-24 04:19
Duplicate of #1431

**Closed by acheong08** 2023-06-24 04:19 UTC
