### ISSUE TITLE
[Bug]: {'detail': {'message': 'Unauthorized - Access token is missing'}}

### ISSUE THREAD

**Issue by RidiculousRonZzz** [acheong08/ChatGPT#774] opened 2023-02-16 02:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

{'detail': {'message': 'Unauthorized - Access token is missing'}}
In Windows
![d6a17ec396e9b02c2db87f17378dcb1](https://user-images.githubusercontent.com/101501006/219250077-fa367c13-0350-4275-8901-6e22f5395da0.png)

### Steps to reproduce the problem

python3 -m revChatGPT.V1
config.json 
`{
    "email": "xxxx@qq.com",
    "password": "xxxx",
    "session_token": "xxxx",
    "access_token": "xxxx"
}`

### What should have happened?

Something wrong with access_token?

### Version where the problem happens

Version 2.2.7

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

**Comment by QPhuGit** [comment] 2023-02-16 02:45
The same error (2.2.7 version)
![image](https://user-images.githubusercontent.com/118596567/219254954-9b0d9273-f81d-447a-a136-b7060097ad96.png)

**Comment by lean-wang** [comment] 2023-02-16 03:09
you can see this issues #769

**Comment by acheong08** [comment] 2023-02-16 06:47
> { "email": "xxxx@qq.com", "password": "xxxx", "session_token": "xxxx", "access_token": "xxxx" }

Don't put both. Only put access_token

**Comment by acheong08** [comment] 2023-02-16 06:49
And don't put session token if you put access_token

**Comment by druphliu** [comment] 2023-02-16 07:54
KeyError: 'accessToken'

**Comment by acheong08** [comment] 2023-02-16 09:29
Use VPN

**Comment by acheong08** [comment] 2023-02-16 09:30
Duplicate of #769

**Closed by acheong08** 2023-02-16 09:30 UTC
