### ISSUE TITLE
[BUG] local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by IbrahimLakhzine** [acheong08/ChatGPT#455] opened 2023-01-11 10:58 UTC
**Description**                                                          
I am getting this message when ruuning the script "local variable 'driver' referenced before assignment".

**Comment by acheong08** [comment] 2023-01-11 11:13
Give the full error message. This says nothing. Probably duplicate of https://github.com/acheong08/ChatGPT/issues/381

**Comment by IbrahimLakhzine** [comment] 2023-01-11 11:17
actually this the only message it gives.

**Comment by acheong08** [comment] 2023-01-11 11:18
Add some print statements in the code. Can't tell what the error is here

**Comment by qcwthu** [comment] 2023-01-11 12:11
Do you use Chrome version 109?

**Comment by IbrahimLakhzine** [comment] 2023-01-11 12:15
i am using chrome Version 108.0.5359.125

**Comment by IbrahimLakhzine** [comment] 2023-01-11 12:45
and also I am using  chromedriver_py-108.0.5359.71

**Comment by FlorianMgs** [comment] 2023-01-11 13:20
Update your chrome version to latest 109, it should work

**Comment by IbrahimLakhzine** [comment] 2023-01-11 13:24
So in this case i should also update chrome drive to latest version, right?

**Comment by IbrahimLakhzine** [comment] 2023-01-11 14:42
Yes it is working now.

**Comment by PeggyFan** [comment] 2023-01-12 19:25
I upgraded to version 109 for my Chrome browser but still got the same error. Also pip installed the package again with the upgrade.

**Comment by spestushko** [comment] 2023-01-16 02:42
@PeggyFan , are you running it with Xvfb or natively?

**Comment by Liu-Angelo** [comment] 2023-01-16 05:03
> 而我正使用chromedriver_py-108.0.5359.71

Spawning browser...
Traceback (most recent call last):
  File "/usr/local/bin/python310/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 475, in get_cf_cookies
    driver = uc.Chrome(
  File "/usr/local/bin/python310/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 246, in __init__
    patcher.auto()
  File "/usr/local/bin/python310/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 130, in auto
    release = self.fetch_release_number()
  File "/usr/local/bin/python310/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 151, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/langstonliu/chatgpt_service.py", line 3, in <module>
    chatbot = Chatbot({
  File "/usr/local/bin/python310/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/usr/local/bin/python310/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 490, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by acheong08** [comment] 2023-01-16 05:23
Duplicate https://github.com/acheong08/ChatGPT/issues/381

**Closed by acheong08** 2023-01-16 05:23 UTC
Labels: bug
