### ISSUE TITLE
"Captcha detected" hampers logging

### ISSUE THREAD

**Issue by reycn** [acheong08/ChatGPT#36] opened 2022-12-05 13:41 UTC
```
Logging in...
Captcha detected
Error refreshing session
can only concatenate str (not "NoneType") to str
...
```
Expected behavior for the difficulty in resolving captcha issue?

<img width="386" alt="image" src="https://user-images.githubusercontent.com/11225092/205651111-49afb2f2-0814-4d1e-ac46-4fbbe96c2cf3.png">

**Comment by acheong08** [comment] 2022-12-05 13:43
I haven't figured out how to do captcha yet. If you know how, could you make a pull request?

If not, perhaps you could write some better error handling for this library. I am currently a but busy and won't be able to dedicate too much time to this until Wednesday.

**Comment by reycn** [comment] 2022-12-05 14:38
Do you @rawandahmad698 have any suggestions?

**Comment by acheong08** [comment] 2022-12-05 14:39
Right now, the best way to do this is to simply wrap the email/password in try except and make it return error on captcha detection. This can then be caught and alerted to the user

**Comment by rawandahmad698** [comment] 2022-12-05 14:42
The original code waits on the user to solve the captcha and then submit it. Unfortunately this is removed on this repo. Check out the original version of PyChatGPT. 

The concatenation error is present because auth.access_token is initially None. Since the option to solve the captcha manually is removed, the script returns and you can't str + None

**Comment by rawandahmad698** [comment] 2022-12-05 14:45
It's a simple svg converted to png with a increased 300% dpi for better visibility. It's very small in size and gets overwritten on subsequent disk writes. So the user can view, write the words and proceed. I can look into removing the png file when it's done.

**Comment by acheong08** [comment] 2022-12-05 14:48
The issue is that you cannot open a png file on a server which most implementations of this library uses. I'm unsure of how to detect this and alert the user to use tokens accordingly

**Comment by rawandahmad698** [comment] 2022-12-05 14:52
That's interesting. People can explore & purchase clean proxies. At MeshMonitors we use https://webshare.io proxies. 

1. A clean IP with no suspicious activity passes their bot detection check. 

2. In a use case (GPTChat for Discord) the user could show the captcha as a discord attachment. 

I really can't know what all of the use cases are. But training a custom ML to solve the captcha is fairly straightforward. Unfortunately i do not have the time, and money to proceed with it.

**Comment by acheong08** [comment] 2022-12-05 14:55
>  But training a custom ML to solve the captcha is fairly straightforward. Unfortunately i do not have the time, and money to proceed with it.

Same here

I'll just wrap it in try except and alert the user that Captcha isn't supported and to use session tokens instead

**Comment by rawandahmad698** [comment] 2022-12-05 14:58
I have 14 stars on my own repo. Add my repo on your github page (🫣) and with 100 or more stars I will do more research and possibly find a solution. 

The reason I want 100 or more is that I want to know that the hours spent on it is worth it. In a way of giving back to the community

**Comment by acheong08** [comment] 2022-12-05 14:58
> I have 14 stars on my own repo. Add my repo on your github page (🫣) and with 100 or more stars I will do more research and possibly find a solution.
> 
> The reason I want 100 or more is that I want to know that the hours spent on it is worth it. In a way of giving back to the community

Totally agree. I will put it up top as a better alternative for CLI use.

**Comment by acheong08** [comment] 2022-12-05 14:59
Closing as not planned

**Closed by acheong08** 2022-12-05 14:59 UTC
Labels: enhancement, help wanted

**Comment by acheong08** [comment] 2022-12-05 15:04
@rawandahmad698 Added right up at the top. I wish you luck
