### ISSUE TITLE
[Bug]: V1 version  context control 

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#785] opened 2023-02-16 11:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

There was no problem with the context control of V1 version in the morning, but now there is no context, the author has modified it

### Steps to reproduce the problem

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19570026/219348013-1a9bd548-6926-45a4-892b-7005766e24bc.png">

### What should have happened?

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19570026/219348005-5568411a-8e57-449d-9377-07a2d291672c.png">

### Version where the problem happens

2.2.6

### What Python version are you running this with?

3.10

### Command Line Arguments

```Shell
chatbot = Chatbot(config={
    "email": "{}".format(random_info['email']),
    "password": "{}".format(random_info['password']),
    "paid": "{}".format(True)
})
```

### Console logs

```Shell
There was no problem with the context control of V1 version in the morning, but now there is no context, the author has modified it
```

**Comment by acheong08** [comment] 2023-02-16 11:08
Could you explain? The screenshots don't look like they're from this repo

**Comment by acheong08** [comment] 2023-02-16 11:17
Duplicate of #782

**Closed by acheong08** 2023-02-16 11:17 UTC
