### ISSUE TITLE
[Bug]:OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403) Not Solved

### ISSUE THREAD

**Issue by SwimmingLiu** [acheong08/ChatGPT#1432] opened 2023-06-20 05:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![Dingtalk_20230620134542](https://github.com/acheong08/ChatGPT/assets/53814462/2428deb0-72f6-4a33-b6b6-9936a163eb39)

### Steps to reproduce the problem

Try to run ask() with V1 API.

### What should have happened?

Is should work:)

### Version where the problem happens

Tried 6.4.0(latest)
![Dingtalk_20230620134711](https://github.com/acheong08/ChatGPT/assets/53814462/8071f7ea-7ea3-4319-8a7c-92db2239f165)

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 731, in __check_response
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bypass.churchless.tech/conversation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/gpt4_test.py", line 222, in <module>
    get_slice_thread_io(token)
  File "/root/gpt4_test.py", line 200, in get_slice_thread_io
    get_content(token[0], server)
  File "/root/gpt4_test.py", line 148, in get_content
    for data in chatbot.ask(prompt):
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 618, in ask
    yield from self.post_messages(
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 571, in post_messages
    yield from self.__send_request(
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 406, in __send_request
    self.__check_response(response)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 90, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 738, in __check_response
    raise error from ex
revChatGPT.typings.Error: OpenAI: {"detail":"Our systems have detected unusual activity from your system. Please try again later."} (code: 403)
```

**Comment by acheong08** [comment] 2023-06-20 06:23
Duplicate of #1431

**Closed by acheong08** 2023-06-20 06:23 UTC
