### ISSUE TITLE
[BUG]after runing the Chrome browser window keeps opening and closing

### ISSUE THREAD

**Issue by jackyzyaq** [acheong08/ChatGPT#430] opened 2023-01-07 16:21 UTC
**Describe the bug**
application can runing with env. Info as below:
 - os: Mac OS 13.0.1 (22A400)
 - python:3.8.7
 - chromedriver:108.0.5359.71
 - ChatGPT Version: 0.0.49.1

but after runing the Chrome browser window keeps opening and closing with this console log :
_Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned._

![image](https://user-images.githubusercontent.com/26595866/211160332-a1e87194-362f-418e-9106-6ac65f35ce30.png)

Greatly appreciated that you guys may help out to check this issue.

**Comment by studentofcoding** [comment] 2023-01-08 04:12
> **Describe the bug** application can runing with env. Info as below:
> 
> * os: Mac OS 13.0.1 (22A400)
> * python:3.8.7
> * chromedriver:108.0.5359.71
> * ChatGPT Version: 0.0.49.1
> 
> but after runing the Chrome browser window keeps opening and closing with this console log : _Logging in... Spawning browser... Browser spawned. Found Cloudflare Cookie! Spawning browser... Browser spawned. Found Cloudflare Cookie! Spawning browser... Browser spawned._
> 
> ![image](https://user-images.githubusercontent.com/26595866/211160332-a1e87194-362f-418e-9106-6ac65f35ce30.png)
> 
> Greatly appreciated that you guys may help out to check this issue.

I've recently got this issue too, and it's because my internet is slow

Have you changed your wifi connection?

**Comment by acheong08** [comment] 2023-01-08 04:12
I don't think it's because of slow internet

**Comment by acheong08** [comment] 2023-01-08 04:13
Duplicate of https://github.com/acheong08/ChatGPT/issues/385

**Closed by acheong08** 2023-01-08 04:13 UTC
Labels: bug
