### ISSUE TITLE
[Bug]: Empty messages in console & strange responses in the interface

### ISSUE THREAD

**Issue by Egnod** [acheong08/ChatGPT#881] opened 2023-02-24 19:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When working with V1, I found the following problem: the answer is empty, although in the account chat.openai.com he is present. An error was also found when the answer is still empty, and a cropped message arrives in the ChatGPT account, although if you write the question yourself, and not through lib, everything is fine. I attach screenshots.

1. [Empty message](https://paste.pics/e0da01c10febc8b70ff1908b4b196d2a)
2. [Strange answer received with lib request](https://paste.pics/39957c70ebfd1f8d3694891ceab466e6) vs. [Normal response](https://paste.pics/e3438be8a6656b3908f23f338b74b29f)

### Steps to reproduce the problem

1. Create instance V1 ChatBot
2. Call method .ask(prompt)
3. Receive empty message 

### What should have happened?

After call .ask method I receive full and normal answer from ChatGPT

### Version where the problem happens

2.3.8

### What Python version are you running this with?

3.9.16

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
(.venv) trust@trusted-umbra-7zu:~/Projects/gpt-bot$ python3 -m gpt_bot.bots.user.user_bot
[nltk_data] Downloading package stopwords to /home/trust/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/trust/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /home/trust/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
{'message': '', 'conversation_id': 'e9a0a61b-7321-453c-89fa-99e3d6a24a49', 'parent_id': '0551e2b6-f304-4d7f-9346-575431fbaceb'}
```

**Comment by Egnod** [comment] 2023-02-24 21:59
> Sometimes it happens when there is a server issue; it should usually come with an error message. Have you tried when the server is available, you can check that on the open ai website.

Yes, and the second screen is just the case when I get an empty message through the lib, and in the dialog chat.openai.com I have some kind of nonsense - a "bitten" message

**Comment by acheong08** [comment] 2023-02-25 03:01
The first response is always blank since it's a stream

**Comment by acheong08** [comment] 2023-02-25 03:01
You have to loop through the stream and wait for the last response

**Comment by linhandev** [comment] 2023-02-25 07:09
I noticed the second response is always the user's input. Thus when using the V1 cli, chatgpt's response will be prefixed with user's prompt. Is this intended behavior?

**Comment by acheong08** [comment] 2023-02-25 15:51
The API behavior changed. Fixed on newest release

**Closed by acheong08** 2023-02-25 15:51 UTC
