### ISSUE TITLE
[Bug]: OpenAIAuth.Error

### ISSUE THREAD

**Issue by alphaokxyz** [acheong08/ChatGPT#952] opened 2023-02-28 09:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

cant use command line

### Steps to reproduce the problem

python3 -m revChatGPT.V1

### What should have happened?

reply

### Version where the problem happens

2.3.15

### What Python version are you running this with?

3.8.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
root@vps1:~# python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Logging in...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 936, in <module>
    main(configure())
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 860, in main
    chatbot = Chatbot(
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 174, in __init__
    self.__check_credentials()
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 201, in __check_credentials
    raise error
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 199, in __check_credentials
    self.__login()
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 52, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 339, in __login
    auth.begin()
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth.py", line 247, in __part_five
    raise Error(
OpenAIAuth.Error
```

### Additional information

help

**Comment by acheong08** [comment] 2023-02-28 11:19
Duplicate of https://github.com/acheong08/ChatGPT/issues/931

**Closed by acheong08** 2023-02-28 11:19 UTC
