### ISSUE TITLE
[BUG]can not log in

### ISSUE THREAD

**Issue by Chastex** [acheong08/ChatGPT#118] opened 2022-12-07 03:56 UTC
**Describe the bug**
Logging in...
Invalid credentials
Error refreshing session: 
Error logging in

**version**
revChatGPT-0.0.31

**Comment by 7Cecil** [comment] 2022-12-07 03:59
I'm having the same issue on windows.

**Comment by acheong08** [comment] 2022-12-07 04:00
I suppose this is confirmed to be a bug. Try using session tokens instead.

**Comment by acheong08** [comment] 2022-12-07 04:02
To use session tokens, delete your current config and follow the instructions here
https://github.com/acheong08/ChatGPT/wiki/Setup#token-authentication

**Comment by 7Cecil** [comment] 2022-12-07 04:02
I also tried tokens and it didn't work.

**Comment by acheong08** [comment] 2022-12-07 04:03
Have you tried tokens without the email/password in your config?

**Comment by acheong08** [comment] 2022-12-07 04:03
The system prioritizes email/password over tokens so having both would override the tokens

**Comment by acheong08** [comment] 2022-12-07 04:04
If all else fails, try with https://github.com/rawandahmad698/PyChatGPT which has better support for CLI use and captcha

**Comment by 7Cecil** [comment] 2022-12-07 04:04
Yes, when i used tokens i also deleted the email and password.

**Comment by Chastex** [comment] 2022-12-07 04:05
with session_token ,error info "Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com."

**Comment by acheong08** [comment] 2022-12-07 04:06
> Yes, when i used tokens i also deleted the email and password.

It's difficult for me to fix because I can't replicate it.

> If all else fails, try with [rawandahmad698/PyChatGPT](https://github.com/rawandahmad698/PyChatGPT) which has better support for CLI use and captcha

If this doesn't work, then it is something wrong with your account.

**Comment by acheong08** [comment] 2022-12-07 04:06
> with session_token ,error info "Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at [beta.openai.com](https://beta.openai.com)."

Oh did the official API get released?

**Comment by acheong08** [comment] 2022-12-07 04:08
I'll experiment with the official API keys

**Comment by somenothing** [comment] 2022-12-07 05:38
I‘ve done a few tests and found that usually the reason for not being able to log in is a network problem. You can check if the ChatGPT website can be accessed properly on the current network. 
After using the proxy, you can log in normally using the email - password.

Perhaps developers could add more error handling to throw more specific errors rather than simple login errors.

**Comment by acheong08** [comment] 2022-12-07 05:40
I will work on that once I have time. 
> Perhaps developers could add more error handling to throw more specific errors rather than simple login errors.

This is a major issue with this project: bad error handling. If anyone is willing to help me with this, thank you.

**Comment by Chastex** [comment] 2022-12-07 05:40
> I‘ve done a few tests and found that usually the reason for not being able to log in is a network problem. You can check if the ChatGPT website can be accessed properly on the current network. After using the proxy, you can log in normally using the email - password.
> 
> Perhaps developers could add more error handling to throw more specific errors rather than simple login errors.

thanks

**Comment by acheong08** [comment] 2022-12-07 09:19
I have added more verbose error handing with `--debug`. After updating to the latest version (0.0.31.3 atm) run `python3 -m revChatGPT --debug` and it should show better errors.

**Comment by Chastex** [comment] 2022-12-07 09:51
i found the website added a new api interface "https://chat.openai.com/api/auth/session"

**Comment by acheong08** [comment] 2022-12-07 09:55
That's interesting. Will look into implementing that

**Comment by acheong08** [comment] 2022-12-07 09:56
> i found the website added a new api interface "[chat.openai.com/api/auth/session](https://chat.openai.com/api/auth/session)"

Hmm. I already implemented this in refresh_session()

**Comment by acheong08** [comment] 2022-12-07 15:34
Closing in favor of  unified tracker:
https://github.com/acheong08/ChatGPT/issues/134

**Closed** 2022-12-07 15:35 UTC
Labels: bug, help wanted, good first issue
