### ISSUE TITLE
openai.error.RateLimitError: Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com. [BUG]

### ISSUE THREAD

**Issue by xyxxmb** [acheong08/ChatGPT#589] opened 2023-02-07 09:26 UTC
**Description**

**Steps to Reproduce**

**Expected behavior**

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: [e.g. Linux, MacOS, Windows]
 - Python version: python -V
 - ChatGPT Version: pip3 show revChatGPT

**Additional context**

**Comment by acheong08** [comment] 2023-02-07 09:28
Duplicate of 
- https://github.com/acheong08/ChatGPT/issues/583

**Closed by acheong08** 2023-02-07 09:28 UTC
Labels: bug, duplicate
