### ISSUE TITLE
[Bug]: 404 Not Found<

### ISSUE THREAD

**Issue by sihai2933** [acheong08/ChatGPT#1093] opened 2023-03-09 01:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

revChatGPT.V1.Error: OpenAI: 
404 Not Found

### Steps to reproduce the problem

 (code: 404)

### What should have happened?

revChatGPT.V1.Error: OpenAI: 
404 Not Found

### Version where the problem happens

3.8.2

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
run
```

### Console logs

```Shell
D:\PycharmProjects\pythonProject\venv\Scripts\python.exe D:/PycharmProjects/pythonProject/main.py
Chatbot: 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a4f9d0e2a956bee","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

Traceback (most recent call last):
  File "D:\PycharmProjects\pythonProject\main.py", line 23, in <module>
    for data in chatbot.ask(
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\revChatGPT\V1.py", line 509, in ask
    self.__check_response(response)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\revChatGPT\V1.py", line 630, in __check_response
    raise Error(
revChatGPT.V1.Error: OpenAI: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a4f9d0e2a956bee","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>
 (code: 404)
```

**Comment by acheong08** [comment] 2023-03-09 01:56
Duplicate of #1093

**Closed by acheong08** 2023-03-09 01:56 UTC
