### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Shiro2568** [acheong08/ChatGPT#283] opened 2022-12-12 14:58 UTC
When sending a message to the bot, an error appears - 
```
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
```

Can you suggest what to do at this moment?

**Comment by acheong08** [comment] 2022-12-12 14:59
A lot of things has changed. Please refer to the readme notice and https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by acheong08** [comment] 2022-12-12 15:00
This is a duplicate of https://github.com/acheong08/ChatGPT/issues/261

**Closed by acheong08** 2022-12-12 15:00 UTC
Labels: bug

**Comment by Shiro2568** [comment] 2022-12-12 19:01
Thank u!
