### ISSUE TITLE
[Bug]: 502 Bad Gateway

### ISSUE THREAD

**Issue by IbrahimLakhzine** [acheong08/ChatGPT#792] opened 2023-02-16 19:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>  
<hr><center>nginx/1.18.0 (Ubuntu)</center> 
</body>
</html>

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

getting the response

### Version where the problem happens

V1

### What Python version are you running this with?

more than 3.8

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
.
```

### Additional information

.

**Comment by CharleoY** [comment] 2023-02-16 20:32
Same here

**Comment by acheong08** [comment] 2023-02-16 23:45
Update to https://github.com/acheong08/ChatGPT/releases/tag/2.3.0. Old servers got overloaded

**Comment by acheong08** [comment] 2023-02-16 23:45
Duplicate of https://github.com/acheong08/ChatGPT/issues/788

**Closed by acheong08** 2023-02-16 23:45 UTC

**Comment by acheong08** [comment] 2023-02-16 23:46
Another possible issue could be that your DNS is outdated. Flush cache and check `dig chatgpt.duti.tech`
