### ISSUE TITLE
[Bug]: for V1 revChatGPT.typings.Error: OpenAI: error code: 1020 (code: 403)

### ISSUE THREAD

**Issue by maminiainalaic** [acheong08/ChatGPT#1331] opened 2023-04-15 18:43 UTC
### What happened?

revChatGPT.typings.Error: OpenAI: error code: 1020 (code: 403)

**Comment by Helohi** [comment] 2023-04-15 18:58
+

**Comment by acheong08** [comment] 2023-04-16 07:06
Duplicate of #1336

**Closed by acheong08** 2023-04-16 07:06 UTC
Labels: V1
