### ISSUE TITLE
[Bug]:  revChatGPT.V1 - ERROR - ask - Field missing NoneType: None 'str' object has no attribute 'get' 

### ISSUE THREAD

**Issue by zhimin-z** [acheong08/ChatGPT#936] opened 2023-02-27 17:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I run with `revChatGPT==2.3.14`, this throws the following errors:
![image](https://user-images.githubusercontent.com/8592144/221636712-7c6bad0b-99f0-4be2-9ffa-aee5126bb3c4.png)

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/8592144/221637398-935f7c92-21cc-41e6-a14f-4f4adad00b81.png)

### What should have happened?

Nothing throws.

### Version where the problem happens

2.3.14

### What Python version are you running this with?

3.9.13

### What is your operating system?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
See above
```

### Additional information

I rolled back to `2.3.13` and this message disappears magically.

**Comment by devkoriel** [comment] 2023-02-27 17:31
ChatGPT is down now. That's why.

**Comment by acheong08** [comment] 2023-02-28 00:44
Duplicate of https://github.com/acheong08/ChatGPT/issues/932

**Closed by acheong08** 2023-02-28 00:44 UTC
