### ISSUE TITLE
[Bug]: Stopped working today V1 Standard ChatGPT

### ISSUE THREAD

**Issue by Swiftgti** [acheong08/ChatGPT#1414] opened 2023-06-12 17:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Since las hour don't work any more 

### Steps to reproduce the problem

using V1 Standard ChatGPT, try so send any prompt.

### What should have happened?

minutes past until you get phyton error

### Version where the problem happens

ALL. olders and latest

### What Python version are you running this with?

3.11

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by vgdh** [comment] 2023-06-13 03:55
please add the logs maybe it is the same thing as  #1415

**Comment by Swiftgti** [comment] 2023-06-13 04:46
Hi yes, is same error. 
What can I do ?
Tomorrow I post the log, but I remember it, is the same. 
Thanks

**Comment by acheong08** [comment] 2023-06-13 09:55
Duplicate of #1415

**Closed by acheong08** 2023-06-13 09:55 UTC
